### PR TITLE
fix: preserve FAL video URLs for Rendi cloud backend

### LINKED ISSUE #78: Rendi backend fails when video is downloaded to temp file instead of keeping URL
## Description

When using the Rendi cloud backend with `render()`, generated videos from FAL are downloaded to local temp files before being passed to editly. Rendi backend then fails because it requires URLs, not local file paths.

## Error

```
✓ video done (72.5s)
⏳ generating editly with ffmpeg (~15s)
[editly] using backend: rendi
error: Rendi backend requires URLs, got local path: /var/folders/.../varg-xxx.mp4
```

## Reproduction

```tsx
import { render, Render, Clip, Video } from 'vargai/react'
import { fal } from 'vargai/ai'
import { createRendiBackend } from 'vargai/editly'

const backend = createRendiBackend()

await render(
  <Render width={1080} height={1920}>
    <Clip duration={5}>
      <Video prompt="cute orange cat waving hello" model={fal.videoModel('kling-v2.5')} />
    </Clip>
  </Render>,
  { backend }
)
```

## Expected Behavior

When using Rendi backend, FAL/Elevenlabs results should stay as URLs and be passed directly to Rendi without downloading to local temp files.

## Actual Behavior

1. FAL generates video → returns URL ✅
2. vargai downloads video to local temp file ❌
3. Passes local path to editly/Rendi
4. Rendi fails with "requires URLs, got local path"

## Stack Trace

```
at ensureUrl (vargai/src/ai-sdk/providers/editly/rendi/index.ts:173)
at ffprobe (vargai/src/ai-sdk/providers/editly/rendi/index.ts:19)
at getFirstVideoInfo (vargai/src/ai-sdk/providers/editly/index.ts:38)
at editly (vargai/src/ai-sdk/providers/editly/index.ts:364)
at renderRoot (vargai/src/react/renderers/render.ts:226)
```

## Suggested Fix

In the react renderer, check if backend is Rendi before downloading generated content:
- If local backend → download to temp files (current behavior)
- If Rendi backend → keep as URLs

Relevant files:
- `src/react/renderers/video.ts` - where video results are handled
- `src/react/renderers/render.ts` - where editly is called

## Environment

- vargai: 0.4.0-alpha34
- Runtime: Bun via Next.js API route
- Backend: Rendi cloud

### PR DESCRIPTION
**Pull request by caffeinum**
## Summary

Fixes #78 - Rendi backend now works with FAL-generated videos by using URLs directly instead of downloading to temp files.

## Changes

- Add optional `url` property to `GeneratedVideo` interface
- FAL provider preserves video URLs in response (`videoUrls` array)
- `RenderContext` includes `backend` for cloud detection
- `isCloudBackend()` helper identifies backends requiring URLs
- Video/image renderers return URL directly when using cloud backend

## How it works

Before:
```
FAL returns URL → download to Uint8Array → save to temp file → Rendi fails (needs URL)
```

After:
```
FAL returns URL → preserve in GeneratedVideo.url → renderer returns URL for Rendi → works
```

### CODE REVIEW

**Comment by caffeinum** [comment]
@coderabbitai review

**Comment by caffeinum** [comment]
@coderabbitai review

File: src/react/renderers/video.ts [hunk 1]
```diff
@@ -103,11 +98,13 @@ async function resolvePrompt(
...
   ctx: RenderContext,
-): Promise<string> {
+): Promise<File> {
   const props = element.props as VideoProps;
 
   if (props.src && !props.prompt) {
-    return props.src;
+    return typeof props.src === "string" && props.src.startsWith("http")
+      ? File.fromUrl(props.src)
+      : File.fromPath(props.src);
```
Comment (SecurityQQ) [inline src/react/renderers/video.ts]: Let's make a serialization function from props to file.
