### PR TITLE
fix: burnCaptions subtitles filter and music cache format

### LINKED ISSUE #97: Bug: Music cache deserialization fails - File has no data source
## Description

When music is loaded from cache, the `File` object is created without proper data, causing the error:

```
Error: File has no data source
```

## Steps to Reproduce

1. Generate a video with music (first run succeeds)
2. Run the same video again (cache hit)
3. Error occurs when trying to use the cached music file

## Root Cause

The cache stores `Uint8Array` as a serialized object:

```json
{"value":{"__type":"Uint8Array","data":"SUQzBAA..."}}
```

When retrieved in `renderMusic()` (src/react/renderers/music.ts:41-52), the `uint8Array` field is not properly deserialized back to a `Uint8Array`. The `File.fromGenerated()` then receives an object that doesn't have valid data.

## Location

- `src/react/renderers/music.ts` - cache retrieval logic
- `src/ai-sdk/file-cache.ts` - cache serialization/deserialization

## Expected Behavior

Cached music files should be properly deserialized and usable on subsequent runs.

## Workaround

Delete the cached music file:
```bash
rm ".cache/ai/__type___music___prompt___<prompt>___model___music_v1__.json"
```

### LINKED ISSUE #98: Bug: burnCaptions fails with local backend - subtitles filter cannot fetch remote URLs
## Description

When using the local ffmpeg backend with captions, the `burnCaptions` function uploads the ASS file to R2 storage, then tries to use that URL in the ffmpeg `subtitles` filter. Local ffmpeg cannot fetch remote subtitle files.

```
ffmpeg ... -vf subtitles=https\://s3.varg.ai/tmp/1769813220012-varg-captions.ass
Error: Failed with exit code 234
```

## Steps to Reproduce

1. Create a video with `<Captions>` component
2. Run with local backend: `--backend=local`
3. Error occurs at the captions burn step

## Root Cause

In `src/react/renderers/burn-captions.ts`, when there's no explicit backend or when using local backend:
1. The video and ASS file are uploaded to storage (R2)
2. The ffmpeg command uses those URLs
3. But ffmpeg's `subtitles` filter only supports local file paths, not HTTP URLs

The Rendi backend can handle remote URLs because it runs in the cloud with access to fetch files. Local ffmpeg cannot.

## Location

- `src/react/renderers/burn-captions.ts`

## Expected Behavior

- Local backend: Keep ASS file local, use local file path in subtitles filter
- Rendi backend: Upload to storage, use URLs

## Suggested Fix

Check the backend type before deciding whether to upload:

```typescript
if (backend.name === 'local') {
  // Use local file paths
} else {
  // Upload to storage and use URLs
}
```

### PR DESCRIPTION
**Pull request by SecurityQQ**
## Summary

Fixes two bugs related to captions rendering and music caching:

- **Fix #97**: Handle old music cache format (bare `Uint8Array`) in addition to new format (`{uint8Array, url, mediaType}`) to prevent "File has no data source" error when loading cached music

- **Fix #98**: `burnCaptions` now correctly detects cloud vs local backend using `backend.name` instead of checking if backend is defined. For cloud backends (Rendi), pass raw URL to let the backend replace with input placeholder. For local backend, escape the path for FFmpeg filter syntax.

### `src/react/renderers/burn-captions.ts`
- Fix `isCloud` check: use `backend.name !== "local"` instead of `options.backend !== undefined`
- For cloud backends: pass raw URL in subtitles filter so Rendi can replace with `{{in_2}}` placeholder
- For local backend: escape path with backslashes and colons for FFmpeg filter syntax

### `src/react/renderers/music.ts`
- Add backwards-compatible cache format handling
- Check if cached value is bare `Uint8Array` (old format) or object with `uint8Array` property (new format)

## Testing

Verified both fixes work:
- Rendi backend: subtitles filter uses `{{in_2}}` placeholder correctly
- Local backend: subtitles filter uses escaped local file path
- Old music cache format is handled gracefully

### CODE REVIEW

File: src/react/renderers/music.ts [hunk 1]
```diff
@@ -40,16 +40,21 @@ export async function renderMusic(
...
-        uint8Array: Uint8Array;
-        url?: string;
-        mediaType?: string;
-      };
-      audio = {
-        uint8Array: cachedAudio.uint8Array,
-        url: cachedAudio.url,
-        mediaType: cachedAudio.mediaType,
-      };
+      // Handle both old cache format (bare Uint8Array) and new format ({uint8Array, url, mediaType})
```
Comment (caffeinum) [inline src/react/renderers/music.ts]: maybe just drop old cache?

File: src/react/renderers/burn-captions.ts [hunk 2]
```diff
@@ -69,7 +69,9 @@ export async function burnCaptions(
   const { video, assPath, outputPath = "output.mp4", verbose } = options;
   const captions: FFmpegOutput = { type: "file", path: assPath };
 
-  const isCloud = options.backend !== undefined;
+  // Resolve backend first so we can check if it's cloud or local
+  const backend = options.backend ?? localBackend;
+  const isCloud = backend.name !== "local";
```
Comment (caffeinum) [inline src/react/renderers/burn-captions.ts:76]: maybe add comment that it's a hack and we eventually wanna abstract it
